defaultTargets = ["ENNRealArith", "ENNRealTest"]
name = "ennreal-arith"
testDriver = "TestRunner"
version = "0.1.0"

[[lean_lib]]
name = "ENNRealArith"

[[lean_lib]]
name = "ENNRealTest"

[[lean_exe]]
name = "TestRunner"

[[require]]
name = "mathlib"
scope = "leanprover-community"
