defaultTargets = ["ennreal"]
name = "ennreal"
version = "0.1.0"

[[lean_lib]]
name = "Ennreal"

[[lean_exe]]
name = "ennreal"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
